---
application:
  name: "wordpressfora2sidedmarket"
  project: "genericwp"
  organization: "QoveryCommunity"
  storage:
  - name: "uploads"
    size: "10"
    type: "ssd"
    mount_point: "/var/www/html/wp-content/uploads"
databases:
- type: "MYSQL"
  name: "wordpress"
  version: "8.0"
routers:
- name: "main-wordpressfora2sidedmarket"
  routes:
  - application_name: "wordpressfora2sidedmarket"
    paths:
    - "/*"
