---
application:
  name: "wordpressfora2sidedmarket"
  project: "wordpressTest"
  organization: "QoveryCommunity"
  storage:
  - name: "stones"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/stones"
databases:
- type: "MYSQL"
  name: "flints"
  version: "5.6"
routers:
- name: "main-wordpressfora2sidedmarket"
  routes:
  - application_name: "wordpressfora2sidedmarket"
    paths:
    - "/*"
