---
application:
  name: "wordpressfora2sidedmarket"
  project: "wordpress-market"
  organization: "QoveryCommunity"
  storage:
  - name: "quinn"
    size: "2000"
    type: "slow_hdd"
    mount_point: "/mnt/quinn"
databases:
- type: "MYSQL"
  name: "fred"
  version: "8.0"
routers:
- name: "main-wordpressfora2sidedmarket"
  routes:
  - application_name: "wordpressfora2sidedmarket"
    paths:
    - "/*"
