---
application:
  name: "wordpressfora2sidedmarket"
  project: "wordpress-market"
  organization: "QoveryCommunity"
  storage:
  - name: "poiuy"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/poiuy"
databases:
- type: "MYSQL"
  name: "qwerty"
  version: "8.0"
routers:
- name: "main-wordpressfora2sidedmarket"
  routes:
  - application_name: "wordpressfora2sidedmarket"
    paths:
    - "/*"
