---
application:
  name: "eatmypoop"
  project: "eatmypoop"
  organization: "QoveryCommunity"
  storage:
  - name: "fred"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/fred"
databases:
- type: "MYSQL"
  name: "cooper"
  version: "5.6"
routers:
- name: "main-eatmypoop"
  routes:
  - application_name: "eatmypoop"
    paths:
    - "/*"
