---
application:
  name: "wordpress-market"
  project: "wordpress-market"
  organization: "QoveryCommunity"
  storage:
  - name: "poq"
    size: "2000"
    type: "hdd"
    mount_point: "/mnt/poq"
databases:
- type: "MYSQL"
  name: "qwack"
  version: "8.0"
routers:
- name: "main-wordpress-market"
  routes:
  - application_name: "wordpress-market"
    paths:
    - "/*"
